src/features/analytics/api/factory.ts
src/features/analytics/api/hooks/useQueryWeeklyReport.ts
src/features/analytics/api/repository.ts
src/features/analytics/api/types.ts
src/features/manage/components/ManagePresenter.tsx
src/features/manage/components/ManageQuestCard.tsx
src/features/manage/components/ManageQuestSearchModal,.tsx
src/features/manage/new/components/NewPresenter.tsx
src/features/quests/api/factory.ts
src/features/quests/api/hooks/useQueryQuest.ts
src/features/quests/api/repository.ts
src/features/quests/api/types.ts
src/features/quests/components/QuestBoardNoData.tsx
src/features/quests/components/QuestList.tsx
src/features/quests/components/QuestListNoData.tsx
src/features/quests/components/QuestsPresenter.tsx

- issue #42 
- `./src/api`のリファクタリング
- `useQuery`時のLoading時の挙動を適切にハンドリング
- 色々動かしてみて確認お願いします。

[Web] ./src/api配下のリファクタリングとQuery時の挙動の修正

---

src/features/manage/api/model.ts
src/features/manage/common/constant/constant.ts
src/features/manage/components/ManageDayOfTheWeekCheckBox.tsx
src/features/manage/components/ManagePresenter.tsx
src/features/manage/components/ManageQuestCard.tsx
src/features/manage/components/ManageQuestSearchModal,.tsx
src/features/manage/edit/components/EditPresenter.tsx
src/features/manage/new/components/NewDayOfTheWeek.tsx
src/features/manage/new/components/NewPresenter.tsx
src/features/quests/api/model.ts

- #42 
- `date` -> `day`に修正しました。
- ただし、`./api`配下はバックエンドとの調整でまだしていません。（このPRはこれでマージはします）
- ちゃんと動くか確認お願いします！

[Web] dateをdayにリネーム

---

src/api/quest/model.ts
src/api/quest/types.ts
src/features/manage/common/funcs/convertEnToJPWeekday.ts
src/features/manage/common/funcs/convertNumberToWeekday.ts
src/features/manage/common/funcs/convertWeekdayToNumber.ts
src/features/manage/components/ManageDayOfTheWeekCheckBox.tsx
src/features/manage/components/ManagePresenter.tsx
src/features/manage/components/ManageQuestCard.tsx
src/features/manage/components/ManageQuestSearchModal,.tsx
src/features/manage/edit/components/EditPresenter.tsx
src/features/manage/new/components/NewDayOfTheWeek.tsx
src/features/manage/new/components/NewPresenter.tsx

- close #58 
- タイトルの通りです。
- フロントとバックを立ち上げいただき、確認お願いします、

[Web] ./apiの`date`を`day`に修正し、さらに型付けも行う。

---

src/features/profile/components/ProfileLogoutModalButton.tsx
src/features/profile/components/ProfilePresenter.tsx
src/features/profile/components/ProfileUserSettingsModalButton.tsx

#88 
プロフィール画面の動作を確かめてください。
特にユーザーネームがカードからはみ出さないことを、画面サイズを変えながら確認してください。

[web]fix:プロフィール画面の修正

---

src/api/quest/model.ts
src/features/quests/components/QuestsPresenter.tsx
src/features/quests/funcs/calcTimer.ts
src/pkg/util/dayjs.ts

[Web] timezoneの修正

---

src/features/analytics/components/AnalyticsBarChart.tsx

- chartjsのグラフの目盛りが小数点になってしまう問題を修正しました
- chartjsのグラフの色や軸ラベルの色が変わりました
- いつものようにブランチを移動して```npm run dev```で確認してください

fix: chartjsの見た目変更

---

src/api/quest/model.ts
src/api/quest/types.ts
src/features/manage/api/quest/hooks/useMutateQuest.ts
src/features/manage/components/ManageQuestCard.tsx
src/features/manage/edit/components/EditPresenter.tsx
src/features/manage/new/components/NewPresenter.tsx
src/features/quests/components/QuestBoard.tsx
src/features/quests/components/QuestList.tsx
src/features/quests/funcs/calcTimer.ts
src/pkg/util/dayjs.ts

- クエスト作成時に`state`をリクエストに含めるように修正
- dayjsの調整

[Web] クエスト作成時のロジックの修正

---

src/features/common/components/ConfirmModal.tsx
src/features/common/components/Menu.tsx
src/features/common/components/header/Header.tsx
src/features/common/components/modal/ModalBase.tsx
src/features/common/components/modal/ModalHeaderCloseButton.tsx
src/features/login/components/LoginForm.tsx
src/features/manage/components/ManageQuestSearchModal,.tsx
src/features/manage/tags/components/TagsEditModal.tsx
src/features/profile/components/ProfileLogoutModal.tsx
src/features/profile/components/ProfileUserSettingModal.tsx

- close #100 
- #42 
- Tanstack Routerのパスの表記ミスの修正
- モーダルの影の部分をどこ押しても閉じるように修正
- モーダルの共通部品をコンポーネント化
- ログイン時、ローディングアニメーションを付与
- バックエンドは`develop`でいつも通り動かせます。

[Web] UIの修正等

---

src/features/profile/components/ProfileExpCard.tsx
src/features/profile/components/ProfileLogoutModalButton.tsx
src/features/profile/components/ProfilePresenter.tsx
src/features/profile/components/ProfileUserSettingsModalButton.tsx

プロフィール画面の経験値バーを作りました。動作はしません。
<progress /> にCSSを適用するにはAutoprefixerをインストールする必要があるみたいです。なのでflowbiteから持ってきました。
https://gihyo.jp/article/2023/07/tailwindcss-practice-02

feat:経験値バーの表示

---

src/features/manage/tags/components/TagsColorDropdown.tsx
src/features/manage/tags/components/TagsDeleteButton.tsx
src/features/manage/tags/components/TagsEditModal.tsx
src/features/manage/tags/components/TagsNewButton.tsx
src/features/manage/tags/components/TagsPresenter.tsx

- 全体的にUIの見た目を修正しました
- タグの新規作成ボタン及びモーダルを追加しました
- ビルドエラーを解消させるためにconsole.logを使用しているところがありますがいずれ消します
- 普通にフロントとバックを立ち上げれば開くと思います

タグページのUI修正

---

src/pkg/util/dayjs.ts

fix: analyticsの日付の表示崩れを修正

---

src/features/analytics/components/AnalyticsCard.tsx
src/features/analytics/components/AnalyticsPresenter.tsx
src/features/analytics/components/AnalyticsSwitchButton.tsx

- 統計ページの文言・フォントサイズの修正
- ボタンの挙動の修正
- いつも通り、動かしてもらえればと思います。

[Web] 統計ページのUIの修正

---

vite.config.ts

[web] pwa, vite.config.tsを修正

---

src/api/quest/model.ts
src/api/quest/types.ts
src/features/manage/components/ManageQuestCard.tsx
src/features/manage/edit/components/EditPresenter.tsx
src/features/manage/new/components/NewPresenter.tsx

- close #123 
- manageのUIの曜日のフォントカラーと余白の調整をしました。チェックおねです。
- クエストのAPIの型の調整をしました。

[Web] manageのUIの微調整とクエストの型の修正

---

src/features/common/components/icons/ClockIcon.tsx
src/features/manage/components/ManageQuestCard.tsx
src/features/quests/components/QuestBoard.tsx
src/features/quests/components/QuestBoardNoData.tsx
src/features/quests/components/QuestBoardTimer.tsx
src/features/quests/components/QuestList.tsx
src/features/quests/components/QuestListItem.tsx
src/features/quests/components/QuestListNoData.tsx
src/features/quests/components/QuestStatusTag.tsx
src/features/quests/components/QuestsPresenter.tsx

- close #127 
- 今日の一覧のUIを刷新しました
- 気になることがあれば何でも皆さんからのコメントをお待ちしております！
- いつも通りフロントとバックを立ち上げてクエストを作ってみたりして見た目の変化を確認してみてください

[Web] 今日の一覧のUI刷新

---

src/features/analytics/components/AnalyticsPresenter.tsx
src/features/entrance/components/EntrancePresenter.tsx
src/features/manage/components/ManagePresenter.tsx
src/features/manage/components/ManageProgressBar.tsx
src/features/manage/components/ManageQuestSearchModalButton.tsx
src/features/manage/edit/components/EditPresenter.tsx
src/features/profile/components/ProfileExpCard.tsx
src/features/profile/components/ProfileLogoutModal.tsx
src/features/profile/components/ProfilePresenter.tsx
src/features/profile/components/ProfileUserSettingModal.tsx
src/features/quests/components/QuestBoard.tsx

モーダルボタンの色、エントランスのボタンが少し左にずれる問題を修正

エントランスやボタン色のcssを一部修正

---

src/features/analytics/components/AnalyticsAIFeedback.tsx
src/features/analytics/components/AnalyticsPresenter.tsx
src/features/common/components/layouts/ContentLayout.tsx
src/features/manage/components/ManageProgressBar.tsx

[Web] UIの微調整

---

src/features/analytics/api/weeklyReport/hooks/useQueryWeeklyReport.ts
src/features/analytics/components/AnalyticsPresenter.tsx

- 上手く統計ページの切り替えができていなかっため修正
- キャッシュがきいてなかったので修正

[Web] 統計ページのスイッチングのバグ修正とAPIの調整

---

src/api/weeklyReport/model.ts
src/api/weeklyReport/types.ts
src/features/analytics/components/AnalyticsBarChart.tsx
src/features/analytics/components/AnalyticsPresenter.tsx

[Web] チャートに失敗数の値を追加

---

src/features/manage/components/ManageDayOfTheWeekButton.tsx
src/features/manage/components/ManageDayOfTheWeekSwitchButton.tsx
src/features/manage/components/ManagePresenter.tsx
src/features/manage/components/ManageQuestCard.tsx
src/features/manage/components/ManageTimetable.tsx
src/features/manage/components/ManageTimetableCard.tsx
src/features/manage/components/ManageTimetableNoData.tsx
src/features/quests/components/QuestsPresenter.tsx

- close #147 
- クエスト管理のページがより分かりやすくなりました！！
- 見た目の確認や直感的に編集できるか、その他バグなどいろいろ触って確認をお願いします！
- いつも通りフロントとバックを立ち上げていただければできると思います！
- タグの実装ができていない間にブランチを切ってしまっていたのでまだタグの色によって枠が変化する部分は実装していないです。今やった方がいいですか？

[Web] 時間割UIの実装

---

package-lock.json
package.json
src/features/common/components/ConfirmModal.tsx
src/features/profile/components/ProfileUserSettingsModalButton.tsx
src/features/profile/settings/components/SettingsPresenter.tsx
src/main.tsx

- #42 
- 設定ページのUIの調整をしました。
- モーダルのボタンの色の修正をしました。

[Web] 設定ページのUIの調整

---

src/features/common/components/ConfirmModal.tsx
tailwind.config.js

- ConfirmModalのhover時の色を修正しました
- いつも通り立ち上げて確認してください！

fix: ConfirmModalのhover時の色修正

---

src/features/manage/components/ManagePresenter.tsx
src/features/manage/components/ManageQuestCard.tsx
src/features/manage/components/ManageSearchTagItem.tsx
src/features/manage/components/ManageSearchTagsDropdown.tsx
src/features/manage/components/ManageTimetable.tsx
src/features/manage/components/ManageTimetableCard.tsx
src/features/manage/components/ManageTimetableNoData.tsx
src/features/manage/edit/components/EditPresenter.tsx
src/features/manage/edit/components/EditTagDropdown.tsx

- #169 
- クエスト管理画面で入力されたタグがついに！表示されるようになりました！！
- いつも通り立ち上げて、タグを入力するとクエストに反映されることを確認してください！

クエスト管理画面のタグの表示

---

public/brand-logo.svg
public/logo.svg
src/features/common/components/BackButton.tsx
src/features/manage/edit/components/EditPresenter.tsx
src/features/manage/new/components/NewPresenter.tsx
src/features/manage/tags/components/TagsPresenter.tsx
src/features/profile/badges/api/badge/hooks/useMutateBadge.ts
src/features/profile/badges/components/BadgeCard.tsx
src/features/profile/badges/components/BadgesPresenter.tsx
src/features/profile/badges/components/badge/Badge.tsx
src/features/profile/badges/components/badge/BadgeSecret.tsx
src/features/profile/components/ProfilePresenter.tsx
src/features/profile/settings/components/SettingsPresenter.tsx

- #42 
やったこと
- バッジページのコンポーネントの修正
- 共通化
- プロパティエラーの解消

[Web] UIのリファクタリングやエラー解消

---

src/api/weeklyReport/model.ts
src/api/weeklyReport/types.ts
src/features/analytics/components/AnalyticsPresenter.tsx

[Web] コンプリート日数ではなく、連続ストリーク日数をもつように

---

package-lock.json
package.json
vite.config.ts

- #188 
- TypeScriptやJSXのトランスパイルに関してのツールを現在の`Babel`より20倍速い`SWC`に移行しました。

[Web] トランスパイラーをBabelからSWCに変更

---

.github/workflows/create-pr-release.yaml

[Web]: PRリリース自動化のためのGithub Actionsを追加

---

src/features/analytics/components/AnalyticsAIFeedback.tsx
src/features/analytics/components/AnalyticsBarChart.tsx
src/features/analytics/components/AnalyticsPresenter.tsx

統計ページのグラフを白枠の中に入れて、凡例を追加しました
画面サイズを色々変えてください
グラフが縦につぶれ気味です

統計グラフのデザイン修正

---

src/features/analytics/components/AnalyticsAIFeedback.tsx
src/features/analytics/components/AnalyticsBarChart.tsx
src/features/analytics/components/AnalyticsPresenter.tsx
src/features/common/components/layouts/FadeInLayout.tsx
src/features/manage/components/ManagePresenter.tsx
src/features/manage/components/ManageQuestSearchModal,.tsx
src/features/manage/components/ManageSearchTagsDropdown.tsx

- #42 
- 統計ページのUIを再度修正しました。
- 少し変わったの分かりますか？感想ください。

[Web] 統計ページのUIを再度修正

---

src/features/manage/components/ManagePresenter.tsx
src/features/manage/components/ManageQuestCard.tsx
src/features/manage/components/ManageQuestSearchModal,.tsx
src/features/manage/components/ManageTimetable.tsx
src/features/manage/components/ManageTimetableCard.tsx
src/features/manage/components/ManageTimetableNoData.tsx

[Web] クエスト管理のカードのUIを修正

---

.github/workflows/test-submodule-ref.yaml
src/features/quests/components/QuestBoard.tsx

[Web] サブモジュール更新のためのワークフローのテスト

---

src/features/analytics/components/AnalyticsAIFeedback.tsx
src/features/analytics/components/AnalyticsPresenter.tsx
src/features/manage/components/ManagePresenter.tsx
src/features/manage/components/ManageQuestCard.tsx
src/features/manage/components/ManageTimetableCard.tsx
src/features/quests/components/QuestListItem.tsx

- #238 
- もう一度UIを直してみました。
- 意見・感想ください。

[Web] クエスト管理のカードUIの修正

---

src/features/manage/common/funcs/toSelectColorLabel.ts
src/features/manage/edit/components/EditPresenter.tsx
src/features/manage/edit/components/EditTagDropdown.tsx
src/features/manage/new/components/NewPresenter.tsx
src/features/manage/new/components/NewTagDropdown.tsx
src/features/manage/tags/components/TagsDeleteButton.tsx
src/features/manage/tags/components/TagsEditButton.tsx
src/features/manage/tags/components/TagsItem.tsx
src/features/manage/tags/components/TagsNewModal.tsx
src/features/manage/tags/components/TagsPresenter.tsx
src/features/quests/components/QuestStatusTag.tsx

[Web] タグ一覧の修正とその他UI修正

---

src/features/analytics/components/AnalyticsAIFeedback.tsx
src/features/analytics/components/AnalyticsPresenter.tsx
src/features/manage/components/ManageDayOfTheWeekSwitchButton.tsx
src/features/manage/components/ManageTimetable.tsx
src/features/profile/components/ProfileCard.tsx
src/features/quests/components/QuestBoardNoData.tsx
src/features/quests/components/QuestList.tsx
src/features/quests/components/QuestListItem.tsx
src/features/quests/components/QuestListNoData.tsx
src/features/quests/components/QuestsPresenter.tsx

[Web] 全体的なUIの修正

---

.github/workflows/update-submodule.yaml

[Web] submodule updateのためのactionsを一部修正

---

.github/workflows/ci.yaml
biome.json
package.json
src/features/common/hooks/useInterval.tsx
src/features/quests/components/QuestBoard.tsx
src/features/quests/components/QuestBoardTimer.tsx
src/features/quests/funcs/time.ts

なし
- タイマー機能のリファクタリング
- その他、ciなど修正

[Web] タイマー機能のリファクタリングとその他修正

---

.gitmodules
README.md
package.json
src/api/badge/type.ts
src/api/quest/types.ts
src/api/tag/type.ts
src/api/user/types.ts
src/api/weeklyReport/types.ts

- none
- git submodulesについて、修正対応を行いました。
- git submodulesについて、READMEに追記しました。

fix: submodulesを入れ直す

---

.github/workflows/update-submodule.yaml

fix: update submodules workflows

---

package.json
pnpm-lock.yaml
src/features/analytics/api/weeklyReport/useMutateWeeklyReport.ts
src/features/manage/api/quest/useMutateQuest.ts
src/features/profile/api/user/useMutateUser.ts
src/features/profile/badges/api/badge/useMutateBadge.ts
src/features/quests/api/quest/useMutateQuest.ts
src/features/tags/api/tag/useMutateTag.ts

- none
- Tanstack Queryを用いた、API通信の修正を行いました。

fix: api handling

---

src/features/profile/badges/components/BadgeCard.tsx
src/features/profile/components/ProfileCard.tsx

- none
- badgeのpatchリクエストのフロント側のエラーの修正をしました。
- pin時のUIの表示崩れの修正をしました。

fix: badge input values and ui

---

package.json
pnpm-lock.yaml
src/api/user/factory.ts
src/api/user/repository.ts
src/features/login/hooks/useMutateUser.tsx
src/features/profile/hooks/useMutateUser.ts
src/main.tsx

- `react-cookie`を用いて、クライアントサイドでcookieを扱えるようにする。

fix auth token

---

package.json
pnpm-lock.yaml
src/api/user/factory.ts
src/api/user/repository.ts
src/features/login/hooks/useMutateUser.tsx
src/features/profile/hooks/useMutateUser.ts
src/main.tsx

Reverts taga3s/Rhythmate-Web#290

Revert "【本番反映】2024-10-04 22:24:33"

---

src/features/manage/common/utils/getCurrentState.ts
src/features/manage/edit/presenters/EditPresenter.tsx
src/features/manage/new/presenters/NewPresenter.tsx

fix: add state to updateQuest

---

src/api/badge/factory.ts
src/api/badge/model.ts
src/api/badge/repository.ts
src/api/badge/types.ts
src/api/quest/types.ts
src/api/tag/type.ts
src/api/user/types.ts
src/api/weeklyReport/types.ts
src/features/badges/components/BadgeCard.tsx
src/features/badges/components/badge/Badge.tsx
src/features/badges/components/badge/BadgeFrame.tsx
src/features/badges/components/badge/BadgeItem.tsx
src/features/badges/hooks/useMutateBadge.ts

fix paths of api schema types 

---

package.json
pnpm-lock.yaml
vite.config.ts

bump vite deps
